name: Deploy FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh user@your-server "cd /path/to/your/app && git pull && docker-compose up --build -d"
