name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -fsSL https://api.render.com/deploy/srv-cul4sh3tq21c73bo64og?key=A0dbeiy0wq4 | bash
