name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          ssh -v -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/fastapi-book-project/
            git pull origin main  # Pull latest changes
            sudo systemctl restart fastapi  # Restart the FastAPI service
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
